add 2 options require_tfvar_file and tfvar_filename to allow for more control over plugin behavior

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -107,7 +107,9 @@ function terraform-run() {
   local DEBUG=${BUILDKITE_PLUGIN_TERRAFORM_DEBUG:-false}
   local IMAGE_NAME=${BUILDKITE_PLUGIN_TERRAFORM_IMAGE:-"hashicorp/terraform"}
   local NO_VALIDATE=${BUILDKITE_PLUGIN_TERRAFORM_NO_VALIDATE:-false}
+  local REQUIRE_TFVAR_FILE=${BUILDKITE_PLUGIN_TERRAFORM_REQUIRE_TFVAR_FILE:-false}
   local SKIP_APPLY_NO_DIFF=${BUILDKITE_PLUGIN_TERRAFORM_SKIP_APPLY_NO_DIFF:-false}
+  local TFVAR_FILENAME=${BUILDKITE_PLUGIN_TERRAFOMR_TFVAR_FILENAME:-}
   local USE_WORKSPACES=${BUILDKITE_PLUGIN_TERRAFORM_USE_WORKSPACES:-false}
   local VERSION=${BUILDKITE_PLUGIN_TERRAFORM_VERSION:-0.13.0}
   local WORKSPACE=${BUILDKITE_PLUGIN_TERRAFORM_WORKSPACE:-default}
@@ -167,11 +169,19 @@ function terraform-run() {
   if [[ "${APPLY_ONLY}" == false ]]; then
     echo "+++ :terraform: :buildkite: :hourglass: Running Terraform plan..."
 
+    # preserve previous behaviour
     if [[ "${USE_WORKSPACES}" == true ]]; then
-      terraform-bin plan -input=false -out tfplan -var-file="${WORKSPACE}-terraform.tfvars"
-    else
-      terraform-bin plan -input=false -out tfplan
+      TFVAR_FILENAME="${TFVAR_FILENAME:-$WORKSPACE-terraform.tfvars}"
     fi
+
+    # now also allow for setting a tfvar file, if not using a workspace
+    unset var_file_args
+    if [[ "${REQUIRE_TFVAR_FILE}" == true ]]; then
+      [[ -n "${TFVAR_FILENAME}" ]] || { echo "REQUIRE_TFVAR_FILE == true, but TFVAR_FILENAME not set!" ; exit 1;}
+      [[ -e "${TFVAR_FILENAME}" ]] || { echo "TFVAR_FILENAME ${TFVAR_FILENAME} not found!" ; exit 1;}
+      var_file_args="-var-file=${TFVAR_FILENAME}"
+    fi
+    terraform-bin plan -input=false "${var_file_args:-}" -out tfplan
 
     # Capture plan output for setting variables and passing as artifacts.
     terraform-bin show tfplan -no-color > tfplan.txt
